---
hosts: '{{ target_host }}'
become: true
tasks:

- name: update cache & install curl
  apt:
    update_cache: true
    name:
      - curl
    state: latest

- name: check if brave keyring exists
  stat:
    path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  register: keyring_file

- name: download brave keyring
  get_url:
    url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
  when: not keyring_file.stat.exists

- name: add brave repository to list of repositories
  copy:
    dest: /etc/apt/sources.list.d/brave-browser-release.list
    content: |
      deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    mode: "0644"

- name: install brave
  apt:
    update_cache: true
    name: brave-browser
    state: present