---
vars_prompt:
  - name: target_host
    prompt: Enter target host IP address or hostname
    private: false
  - name: packages_type
    prompt: Enter the base package set (server_package, workstation_packages, greg_packages)
  - name: admin_username
    prompt: Enter the administrator username on the target system

hosts: '{{ target_host }}'
become: true
tasks:

  - name: create ansible user
    user:
      name: ansible
      groups: root
      create_home: false

  - name: add ansible user ssh key
    authorized_keys:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMYnUNuEnfDgFguU2ZSBLCJE3fq23tBTitYY1RWR8RTi ansible"
      state: present

  - name: enable passwordless sudo for ansible
    lineinfile:
      path: /etc/sudoers
      search_string: "ansible"
      line: "ansible ALL=(ALL) NOPASSWD: ALL"
      validate: "/usr/sbin/visudo -cf %s"

  - name: update cache and upgrade packages
    apt:
      update_cache: true
      upgrade: full
      state: latest

  - name: install essential packages
    apt:
      name: '{{ packages_type }}'
      state: latest

  - name: install brave brave-browser
    import_playbook: install_brave_browser.yaml